
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY app /app
ENV MODEL_PATH=/models/plant-disease-model.h5
EXPOSE 8000
CMD ["uvicorn","model_server:app","--host","0.0.0.0","--port","8000","--workers","1"]